/* compiled from: PG */
public final class awz implements axa {
    private static final char[] a;

    static {
        a = new char[]{'2', '2', '2', '3', '3', '3', '4', '4', '4', '5', '5', '5', '6', '6', '6', '7', '7', '7', '7', '8', '8', '8', '9', '9', '9', '9'};
    }

    public final boolean a(char c) {
        return c >= 'a' && c <= 'z';
    }

    public final boolean b(char c) {
        return c >= '0' && c <= '9';
    }

    public final boolean c(char c) {
        return a(c) || b(c);
    }

    public final char d(char c) {
        switch (c) {
            case 'A':
                return 'a';
            case 'B':
                return 'b';
            case 'C':
                return 'c';
            case 'D':
                return 'd';
            case 'E':
                return 'e';
            case 'F':
                return 'f';
            case 'G':
                return 'g';
            case 'H':
                return 'h';
            case 'I':
                return 'i';
            case 'J':
                return 'j';
            case 'K':
                return 'k';
            case 'L':
                return 'l';
            case 'M':
                return 'm';
            case 'N':
                return 'n';
            case rk.X /*79*/:
                return 'o';
            case 'P':
                return 'p';
            case 'Q':
                return 'q';
            case 'R':
                return 'r';
            case 'S':
                return 's';
            case 'T':
                return 't';
            case 'U':
                return 'u';
            case 'V':
                return 'v';
            case 'W':
                return 'w';
            case 'X':
                return 'x';
            case 'Y':
                return 'y';
            case 'Z':
                return 'z';
            case '\u00c0':
                return 'a';
            case '\u00c1':
                return 'a';
            case '\u00c2':
                return 'a';
            case '\u00c3':
                return 'a';
            case '\u00c4':
                return 'a';
            case '\u00c5':
                return 'a';
            case '\u00c7':
                return 'c';
            case '\u00c8':
                return 'e';
            case '\u00c9':
                return 'e';
            case '\u00ca':
                return 'e';
            case '\u00cb':
                return 'e';
            case '\u00cc':
                return 'i';
            case '\u00cd':
                return 'i';
            case '\u00ce':
                return 'i';
            case '\u00cf':
                return 'i';
            case '\u00d0':
                return 'd';
            case '\u00d1':
                return 'n';
            case '\u00d2':
                return 'o';
            case '\u00d3':
                return 'o';
            case '\u00d4':
                return 'o';
            case '\u00d5':
                return 'o';
            case '\u00d6':
                return 'o';
            case '\u00d7':
                return 'x';
            case '\u00d8':
                return 'o';
            case '\u00d9':
                return 'u';
            case '\u00da':
                return 'u';
            case '\u00db':
                return 'u';
            case '\u00dc':
                return 'u';
            case '\u00dd':
                return 'u';
            case '\u00e0':
                return 'a';
            case '\u00e1':
                return 'a';
            case '\u00e2':
                return 'a';
            case '\u00e3':
                return 'a';
            case '\u00e4':
                return 'a';
            case '\u00e5':
                return 'a';
            case '\u00e7':
                return 'c';
            case '\u00e8':
                return 'e';
            case '\u00e9':
                return 'e';
            case '\u00ea':
                return 'e';
            case '\u00eb':
                return 'e';
            case '\u00ec':
                return 'i';
            case '\u00ed':
                return 'i';
            case '\u00ee':
                return 'i';
            case '\u00ef':
                return 'i';
            case '\u00f0':
                return 'd';
            case '\u00f1':
                return 'n';
            case '\u00f2':
                return 'o';
            case '\u00f3':
                return 'o';
            case '\u00f4':
                return 'o';
            case '\u00f5':
                return 'o';
            case '\u00f6':
                return 'o';
            case '\u00f8':
                return 'o';
            case '\u00f9':
                return 'u';
            case '\u00fa':
                return 'u';
            case '\u00fb':
                return 'u';
            case '\u00fc':
                return 'u';
            case '\u00fd':
                return 'y';
            case '\u00ff':
                return 'y';
            case '\u0100':
                return 'a';
            case '\u0101':
                return 'a';
            case '\u0102':
                return 'a';
            case '\u0103':
                return 'a';
            case '\u0104':
                return 'a';
            case '\u0105':
                return 'a';
            case '\u0106':
                return 'c';
            case '\u0107':
                return 'c';
            case '\u0108':
                return 'c';
            case '\u0109':
                return 'c';
            case '\u010a':
                return 'c';
            case '\u010b':
                return 'c';
            case '\u010c':
                return 'c';
            case '\u010d':
                return 'c';
            case '\u010e':
                return 'd';
            case '\u010f':
                return 'd';
            case '\u0110':
                return 'd';
            case '\u0111':
                return 'd';
            case '\u0112':
                return 'e';
            case '\u0113':
                return 'e';
            case '\u0114':
                return 'e';
            case '\u0115':
                return 'e';
            case '\u0116':
                return 'e';
            case '\u0117':
                return 'e';
            case '\u0118':
                return 'e';
            case '\u0119':
                return 'e';
            case '\u011a':
                return 'e';
            case '\u011b':
                return 'e';
            case '\u011c':
                return 'g';
            case '\u011d':
                return 'g';
            case '\u011e':
                return 'g';
            case '\u011f':
                return 'g';
            case '\u0120':
                return 'g';
            case '\u0121':
                return 'g';
            case '\u0122':
                return 'g';
            case '\u0123':
                return 'g';
            case '\u0124':
                return 'h';
            case '\u0125':
                return 'h';
            case '\u0126':
                return 'h';
            case '\u0127':
                return 'h';
            case '\u0128':
                return 'i';
            case '\u0129':
                return 'i';
            case '\u012a':
                return 'i';
            case '\u012b':
                return 'i';
            case '\u012c':
                return 'i';
            case '\u012d':
                return 'i';
            case '\u012e':
                return 'i';
            case '\u012f':
                return 'i';
            case '\u0130':
                return 'i';
            case '\u0131':
                return 'i';
            case '\u0134':
                return 'j';
            case '\u0135':
                return 'j';
            case '\u0136':
                return 'k';
            case '\u0137':
                return 'k';
            case '\u0138':
                return 'k';
            case '\u0139':
                return 'l';
            case '\u013a':
                return 'l';
            case '\u013b':
                return 'l';
            case '\u013c':
                return 'l';
            case '\u013d':
                return 'l';
            case '\u013e':
                return 'l';
            case '\u013f':
                return 'l';
            case '\u0140':
                return 'l';
            case '\u0141':
                return 'l';
            case '\u0142':
                return 'l';
            case '\u0143':
                return 'n';
            case '\u0144':
                return 'n';
            case '\u0145':
                return 'n';
            case '\u0146':
                return 'n';
            case '\u0147':
                return 'n';
            case '\u0148':
                return 'n';
            case '\u014c':
                return 'o';
            case '\u014d':
                return 'o';
            case '\u014e':
                return 'o';
            case '\u014f':
                return 'o';
            case '\u0150':
                return 'o';
            case '\u0151':
                return 'o';
            case '\u0154':
                return 'r';
            case '\u0155':
                return 'r';
            case '\u0156':
                return 'r';
            case '\u0157':
                return 'r';
            case '\u0158':
                return 'r';
            case '\u0159':
                return 'r';
            case '\u015a':
                return 's';
            case '\u015b':
                return 's';
            case '\u015c':
                return 's';
            case '\u015d':
                return 's';
            case '\u015e':
                return 's';
            case '\u015f':
                return 's';
            case '\u0160':
                return 's';
            case '\u0161':
                return 's';
            case '\u0162':
                return 't';
            case '\u0163':
                return 't';
            case '\u0164':
                return 't';
            case '\u0165':
                return 't';
            case '\u0166':
                return 't';
            case '\u0167':
                return 't';
            case '\u0168':
                return 'u';
            case '\u0169':
                return 'u';
            case '\u016a':
                return 'u';
            case '\u016b':
                return 'u';
            case '\u016c':
                return 'u';
            case '\u016d':
                return 'u';
            case '\u016e':
                return 'u';
            case '\u016f':
                return 'u';
            case '\u0170':
                return 'u';
            case '\u0171':
                return 'u';
            case '\u0172':
                return 'u';
            case '\u0173':
                return 'u';
            case '\u0174':
                return 'w';
            case '\u0175':
                return 'w';
            case '\u0176':
                return 'y';
            case '\u0177':
                return 'y';
            case '\u0178':
                return 'y';
            case '\u0179':
                return 'z';
            case '\u017a':
                return 'z';
            case '\u017b':
                return 'z';
            case '\u017c':
                return 'z';
            case '\u017d':
                return 'z';
            case '\u017e':
                return 'z';
            case '\u017f':
                return 's';
            case '\u0180':
                return 'b';
            case '\u0181':
                return 'b';
            case '\u0182':
                return 'b';
            case '\u0183':
                return 'b';
            case '\u0186':
                return 'o';
            case '\u0187':
                return 'c';
            case '\u0188':
                return 'c';
            case '\u0189':
                return 'd';
            case '\u018a':
                return 'd';
            case '\u018b':
                return 'd';
            case '\u018c':
                return 'd';
            case '\u018d':
                return 'd';
            case '\u0190':
                return 'e';
            case '\u0191':
                return 'f';
            case '\u0192':
                return 'f';
            case '\u0193':
                return 'g';
            case '\u0194':
                return 'g';
            case '\u0196':
                return 'i';
            case '\u0197':
                return 'i';
            case '\u0198':
                return 'k';
            case '\u0199':
                return 'k';
            case '\u019a':
                return 'l';
            case '\u019b':
                return 'l';
            case '\u019c':
                return 'w';
            case '\u019d':
                return 'n';
            case '\u019e':
                return 'n';
            case '\u019f':
                return 'o';
            case '\u01a0':
                return 'o';
            case '\u01a1':
                return 'o';
            case '\u01a4':
                return 'p';
            case '\u01a5':
                return 'p';
            case '\u01ab':
                return 't';
            case '\u01ac':
                return 't';
            case '\u01ad':
                return 't';
            case '\u01ae':
                return 't';
            case '\u01af':
                return 'u';
            case '\u01b0':
                return 'u';
            case '\u01b1':
                return 'y';
            case '\u01b2':
                return 'v';
            case '\u01b3':
                return 'y';
            case '\u01b4':
                return 'y';
            case '\u01b5':
                return 'z';
            case '\u01b6':
                return 'z';
            case '\u01bf':
                return 'w';
            case '\u01cd':
                return 'a';
            case '\u01ce':
                return 'a';
            case '\u01cf':
                return 'i';
            case '\u01d0':
                return 'i';
            case '\u01d1':
                return 'o';
            case '\u01d2':
                return 'o';
            case '\u01d3':
                return 'u';
            case '\u01d4':
                return 'u';
            case '\u01d5':
                return 'u';
            case '\u01d6':
                return 'u';
            case '\u01d7':
                return 'u';
            case '\u01d8':
                return 'u';
            case '\u01d9':
                return 'u';
            case '\u01da':
                return 'u';
            case '\u01db':
                return 'u';
            case '\u01dc':
                return 'u';
            case '\u01de':
                return 'a';
            case '\u01df':
                return 'a';
            case '\u01e0':
                return 'a';
            case '\u01e1':
                return 'a';
            case '\u01e4':
                return 'g';
            case '\u01e5':
                return 'g';
            case '\u01e6':
                return 'g';
            case '\u01e7':
                return 'g';
            case '\u01e8':
                return 'k';
            case '\u01e9':
                return 'k';
            case '\u01ea':
                return 'o';
            case '\u01eb':
                return 'o';
            case '\u01ec':
                return 'o';
            case '\u01ed':
                return 'o';
            case '\u01f0':
                return 'j';
            case '\u01f2':
                return 'd';
            case '\u01f4':
                return 'g';
            case '\u01f5':
                return 'g';
            case '\u01f7':
                return 'w';
            case '\u01f8':
                return 'n';
            case '\u01f9':
                return 'n';
            case '\u01fa':
                return 'a';
            case '\u01fb':
                return 'a';
            case '\u01fe':
                return 'o';
            case '\u01ff':
                return 'o';
            case '\u0200':
                return 'a';
            case '\u0201':
                return 'a';
            case '\u0202':
                return 'a';
            case '\u0203':
                return 'a';
            case '\u0204':
                return 'e';
            case '\u0205':
                return 'e';
            case '\u0206':
                return 'e';
            case '\u0207':
                return 'e';
            case '\u0208':
                return 'i';
            case '\u0209':
                return 'i';
            case '\u020a':
                return 'i';
            case '\u020b':
                return 'i';
            case '\u020c':
                return 'o';
            case '\u020d':
                return 'o';
            case '\u020e':
                return 'o';
            case '\u020f':
                return 'o';
            case '\u0210':
                return 'r';
            case '\u0211':
                return 'r';
            case '\u0212':
                return 'r';
            case '\u0213':
                return 'r';
            case '\u0214':
                return 'u';
            case '\u0215':
                return 'u';
            case '\u0216':
                return 'u';
            case '\u0217':
                return 'u';
            case '\u0218':
                return 's';
            case '\u0219':
                return 's';
            case '\u021a':
                return 't';
            case '\u021b':
                return 't';
            case '\u021c':
                return 'y';
            case '\u021d':
                return 'y';
            case '\u021e':
                return 'h';
            case '\u021f':
                return 'h';
            case '\u0224':
                return 'z';
            case '\u0225':
                return 'z';
            case '\u0226':
                return 'a';
            case '\u0227':
                return 'a';
            case '\u0228':
                return 'e';
            case '\u0229':
                return 'e';
            case '\u022a':
                return 'o';
            case '\u022b':
                return 'o';
            case '\u022c':
                return 'o';
            case '\u022d':
                return 'o';
            case '\u022e':
                return 'o';
            case '\u022f':
                return 'o';
            case '\u0230':
                return 'o';
            case '\u0231':
                return 'o';
            case '\u0232':
                return 'y';
            case '\u0233':
                return 'y';
            default:
                return c;
        }
    }

    public final byte e(char c) {
        if (c >= '0' && c <= '9') {
            return (byte) (c - 48);
        }
        if (c < 'a' || c > 'z') {
            return (byte) -1;
        }
        return (byte) (a[c - 97] - 48);
    }

    public final char f(char c) {
        if (c < 'a' || c > 'z') {
            return c;
        }
        return a[c - 97];
    }
}
