public final class boq {
    public static bor A;
    public static bor B;
    public static bor C;
    public static bor D;
    public static bor E;
    public static bor a;
    public static bor b;
    public static bor c;
    public static bor d;
    public static bor e;
    public static bor f;
    public static bor g;
    public static bor h;
    public static bor i;
    public static bor j;
    public static bor k;
    public static bor l;
    public static bor m;
    public static bor n;
    public static bor o;
    public static bor p;
    public static bor q;
    public static bor r;
    public static bor s;
    public static bor t;
    public static bor u;
    public static bor v;
    public static bor w;
    public static bor x;
    public static bor y;
    public static bor z;

    static {
        bor bor = new bor(cme.a("analytics.service_enabled", false), Boolean.valueOf(false));
        a = new bor(cme.a("analytics.service_client_enabled", true), Boolean.valueOf(true));
        b = bor.a("analytics.log_tag", "GAv4", "GAv4-SVC");
        bor.a("analytics.max_tokens", 60, 60);
        bor bor2 = new bor(cme.a("analytics.tokens_per_sec", Float.valueOf(0.5f)), Float.valueOf(0.5f));
        c = bor.a("analytics.max_stored_hits", 2000, 20000);
        bor.a("analytics.max_stored_hits_per_app", 2000, 2000);
        d = bor.a("analytics.max_stored_properties_per_app", 100, 100);
        e = bor.a("analytics.local_dispatch_millis", 1800000, 120000);
        f = bor.a("analytics.initial_local_dispatch_millis", 5000, 5000);
        bor.a("analytics.min_local_dispatch_millis", 120000, 120000);
        bor.a("analytics.max_local_dispatch_millis", 7200000, 7200000);
        g = bor.a("analytics.dispatch_alarm_millis", 7200000, 7200000);
        h = bor.a("analytics.max_dispatch_alarm_millis", 32400000, 32400000);
        i = bor.a("analytics.max_hits_per_dispatch", 20, 20);
        j = bor.a("analytics.max_hits_per_batch", 20, 20);
        String str = "http://www.google-analytics.com";
        k = bor.a("analytics.insecure_host", str, str);
        str = "https://ssl.google-analytics.com";
        l = bor.a("analytics.secure_host", str, str);
        str = "/collect";
        m = bor.a("analytics.simple_endpoint", str, str);
        str = "/batch";
        n = bor.a("analytics.batching_endpoint", str, str);
        o = bor.a("analytics.max_get_length", 2036, 2036);
        p = bor.a("analytics.batching_strategy.k", bog.BATCH_BY_COUNT.name(), bog.BATCH_BY_COUNT.name());
        str = bol.GZIP.name();
        q = bor.a("analytics.compression_strategy.k", str, str);
        bor.a("analytics.max_hits_per_request.k", 20, 20);
        r = bor.a("analytics.max_hit_length.k", 8192, 8192);
        s = bor.a("analytics.max_post_length.k", 8192, 8192);
        t = bor.a("analytics.max_batch_post_length", 8192, 8192);
        str = "404,502";
        u = bor.a("analytics.fallback_responses.k", str, str);
        v = bor.a("analytics.batch_retry_interval.seconds.k", 3600, 3600);
        bor.a("analytics.service_monitor_interval", 86400000, 86400000);
        w = bor.a("analytics.http_connection.connect_timeout_millis", 60000, 60000);
        x = bor.a("analytics.http_connection.read_timeout_millis", 61000, 61000);
        y = bor.a("analytics.campaigns.time_limit", 86400000, 86400000);
        str = "";
        bor.a("analytics.first_party_experiment_id", str, str);
        bor.a("analytics.first_party_experiment_variant", 0, 0);
        z = new bor(cme.a("analytics.test.disable_receiver", false), Boolean.valueOf(false));
        A = bor.a("analytics.service_client.idle_disconnect_millis", 10000, 10000);
        B = bor.a("analytics.service_client.connect_timeout_millis", 5000, 5000);
        bor.a("analytics.service_client.second_connect_delay_millis", 5000, 5000);
        bor.a("analytics.service_client.unexpected_reconnect_millis", 60000, 60000);
        C = bor.a("analytics.service_client.reconnect_throttle_millis", 1800000, 1800000);
        D = bor.a("analytics.monitoring.sample_period_millis", 86400000, 86400000);
        E = bor.a("analytics.initialization_warning_threshold", 5000, 5000);
    }
}
