package p000;

import com.google.android.gms.common.api.Status;

public final class hgj<R extends gup> extends gum<R> {
    private final Status f16905a;

    public R mo2418a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void mo2419a(guq<? super R> guq__super_R) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public Integer mo2420b() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    Status m19738c() {
        return this.f16905a;
    }
}
