package defpackage;

/* renamed from: bmd */
public final class bmd {
    public long A;
    public boolean B;
    public int C;
    public int D;
    public String E;
    public String F;
    public long G;
    public int H;
    public long I;
    public String J;
    public String K;
    public String L;
    public boolean M;
    public int N;
    public int O;
    public String P;
    public int Q;
    public int R;
    public int S;
    public String T;
    public int U;
    public int V;
    public long W;
    public long X;
    public byte[] Y;
    public boolean Z;
    public String a;
    public String b;
    public String c;
    public int d;
    public String e;
    public edo f;
    public String g;
    public int h;
    public long i;
    public String j;
    public String k;
    public String l;
    public int m;
    public String n;
    public String o;
    public String p;
    public double q;
    public double r;
    public String s;
    public String t;
    public String u;
    public String v;
    public byte[] w;
    public int x;
    public boolean y;
    public int z;
}
