package defpackage;

import com.google.android.gms.common.api.Status;

public final class hgj<R extends gup> extends gum<R> {
    private final Status a;

    public R a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void a(guq<? super R> guq__super_R) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public Integer b() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    Status c() {
        return this.a;
    }
}
